run_name: null
training:
  lr: 0.0001
  restore_ckpt: null
  num_epochs: 5
  data_augmentation: False
  data_size: "all"
  batch_size: 64
  optimizer: "adam"
  num_workers: 0
model: # Any model parameters
  z: 1000
  k : 50
  iter_max : 1500
  iter_save : 500
  run: 0
  train: 1
  overwrite: 0
  loss: "mse" 
  nn_type: "GMVAE_CXR14_V7"
  num_classes : 14
